### ISSUE TITLE
Inputs won't register in games

### ISSUE THREAD

**Issue by kiezeph** [Vooges/Logitech-USB-Shifter#1]
So I've done everything it asked of me but when I load up Asseto Corsa, or Dirt rally and try to set my keybinds for the Shifter no inputs would registed.

Were you able to find a workaround for this?

**Comment by Vooges** [comment]
I've tried both games, and they were both able to bind to the shifter. Based off of the fact that you're experiencing this issue in multiple games, I'm guessing that something went wrong during the setup. Have you verified that the shifter is working correctly by following the steps described in the [testing section of the README](https://github.com/Vooges/Logitech-USB-Shifter?tab=readme-ov-file#testing)?

**Comment by kiezeph** [comment]
Actually turns out I was just using an automatic car in asseto corsa hence why I couldn't shift gears.
Thank you so much thought
